# Generated by Django 5.2.7 on 2025-11-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_assignment_body_alter_assignment_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
        migrations.AddField(
            model_name='submission',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
