# Generated by Django 5.2.7 on 2025-11-16 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_schedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='color',
            field=models.CharField(blank=True, help_text='Optional color for calendar display', max_length=20),
        ),
        migrations.AddField(
            model_name='schedule',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='schedule',
            name='notify_students',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='recurrence_rule',
            field=models.CharField(blank=True, help_text='RRULE string, e.g. FREQ=WEEKLY;BYDAY=MO', max_length=500),
        ),
        migrations.AddField(
            model_name='schedule',
            name='reminder_minutes',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='schedule',
            name='slug',
            field=models.SlugField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='schedule',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
        migrations.AddField(
            model_name='schedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='tags',
            field=models.ManyToManyField(blank=True, to='portal.tag'),
        ),
    ]
